# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AQ - Agility & Quality
description: >-
  Agile development is awesome. Except when it's not. And quality is tricky,
  particularly in software development. This blog covers both topics, sometimes
  at the same time. Focusing on the positive side I won't rant a lot.
  Code is mainly in C++, Python, and occasionally Ruby. The articles are inspired
  by books, talks, and podcasts.
author: rknuus
email: rknuus@gmail.com
url: "https://rknuus.github.io"
google_analytics: UA-159071141-1

# about me
github_username: rknuus

# build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-asciidoc
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - imagesdir=/images/post-images/
    - icons=font
    - source-highlighter=pygments
    - pygments-css=style
    - figure-caption!
permalink: /blog/:year/:month/:day/:title

# The following items will not be processed, by default.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .jekyll-cache/
  - image-sources/
  - Gemfile
  - Gemfile.lock
  - README.md
