name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Jekyll Action
        uses: rknuus/jekyll-action@bugfix/bundler-error
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          PUBLISH_REPO: rknuus/rknuus.github.io
          BUILD_DIR: _site
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1.2.0
        with:
          args: -v -r _site -d _site
      - name: Fail if there were link errors
        if: steps.lc.outputs.exit_code != 0
        run: echo "Link check failed!" && exit 1